name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      # - name: Install NodeJS (already in ubuntu-latest)
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      - name: Install dependencies
        run: npm ci # install locked dependencies
      - name: Run tests
        run: npm test

